[package]
name = "obsidian-lib"
version = "0.2.0"  # Updated version
edition = "2021"

[dependencies]
gtk4 = { version = "0.8", features = ["v4_10"] }  # GTK 4 bindings
clap = { version = "4.5", features = ["derive"] }
